/*
 * Copyright (c) 2019 PANTHEON.tech s.r.o. All rights reserved.
 *
 * CNF-NSM License. For licensing terms please contact sales@pantheon.tech.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

// CNFConfigurationListerExpansion allows custom methods to be added to
// CNFConfigurationLister.
type CNFConfigurationListerExpansion interface{}

// CNFConfigurationNamespaceListerExpansion allows custom methods to be added to
// CNFConfigurationNamespaceLister.
type CNFConfigurationNamespaceListerExpansion interface{}
