// Code generated by adapter-generator. DO NOT EDIT.

package adapter

import (
	"github.com/golang/protobuf/proto"
	"go.cdnf.io/cnf-nsm/plugins/nsmplugin/nsmetadata"
	"go.cdnf.io/cnf-nsm/proto/nsm"
	. "go.ligato.io/vpp-agent/v3/plugins/kvscheduler/api"
)

////////// type-safe key-value pair with metadata //////////

type NSMEndpointKVWithMetadata struct {
	Key      string
	Value    *nsm.NetworkServiceEndpoint
	Metadata *nsmetadata.NsmEndpointMetadata
	Origin   ValueOrigin
}

////////// type-safe Descriptor structure //////////

type NSMEndpointDescriptor struct {
	Name                 string
	KeySelector          KeySelector
	ValueTypeName        string
	KeyLabel             func(key string) string
	ValueComparator      func(key string, oldValue, newValue *nsm.NetworkServiceEndpoint) bool
	NBKeyPrefix          string
	WithMetadata         bool
	MetadataMapFactory   MetadataMapFactory
	Validate             func(key string, value *nsm.NetworkServiceEndpoint) error
	Create               func(key string, value *nsm.NetworkServiceEndpoint) (metadata *nsmetadata.NsmEndpointMetadata, err error)
	Delete               func(key string, value *nsm.NetworkServiceEndpoint, metadata *nsmetadata.NsmEndpointMetadata) error
	Update               func(key string, oldValue, newValue *nsm.NetworkServiceEndpoint, oldMetadata *nsmetadata.NsmEndpointMetadata) (newMetadata *nsmetadata.NsmEndpointMetadata, err error)
	UpdateWithRecreate   func(key string, oldValue, newValue *nsm.NetworkServiceEndpoint, metadata *nsmetadata.NsmEndpointMetadata) bool
	Retrieve             func(correlate []NSMEndpointKVWithMetadata) ([]NSMEndpointKVWithMetadata, error)
	IsRetriableFailure   func(err error) bool
	DerivedValues        func(key string, value *nsm.NetworkServiceEndpoint) []KeyValuePair
	Dependencies         func(key string, value *nsm.NetworkServiceEndpoint) []Dependency
	RetrieveDependencies []string /* descriptor name */
}

////////// Descriptor adapter //////////

type NSMEndpointDescriptorAdapter struct {
	descriptor *NSMEndpointDescriptor
}

func NewNSMEndpointDescriptor(typedDescriptor *NSMEndpointDescriptor) *KVDescriptor {
	adapter := &NSMEndpointDescriptorAdapter{descriptor: typedDescriptor}
	descriptor := &KVDescriptor{
		Name:                 typedDescriptor.Name,
		KeySelector:          typedDescriptor.KeySelector,
		ValueTypeName:        typedDescriptor.ValueTypeName,
		KeyLabel:             typedDescriptor.KeyLabel,
		NBKeyPrefix:          typedDescriptor.NBKeyPrefix,
		WithMetadata:         typedDescriptor.WithMetadata,
		MetadataMapFactory:   typedDescriptor.MetadataMapFactory,
		IsRetriableFailure:   typedDescriptor.IsRetriableFailure,
		RetrieveDependencies: typedDescriptor.RetrieveDependencies,
	}
	if typedDescriptor.ValueComparator != nil {
		descriptor.ValueComparator = adapter.ValueComparator
	}
	if typedDescriptor.Validate != nil {
		descriptor.Validate = adapter.Validate
	}
	if typedDescriptor.Create != nil {
		descriptor.Create = adapter.Create
	}
	if typedDescriptor.Delete != nil {
		descriptor.Delete = adapter.Delete
	}
	if typedDescriptor.Update != nil {
		descriptor.Update = adapter.Update
	}
	if typedDescriptor.UpdateWithRecreate != nil {
		descriptor.UpdateWithRecreate = adapter.UpdateWithRecreate
	}
	if typedDescriptor.Retrieve != nil {
		descriptor.Retrieve = adapter.Retrieve
	}
	if typedDescriptor.Dependencies != nil {
		descriptor.Dependencies = adapter.Dependencies
	}
	if typedDescriptor.DerivedValues != nil {
		descriptor.DerivedValues = adapter.DerivedValues
	}
	return descriptor
}

func (da *NSMEndpointDescriptorAdapter) ValueComparator(key string, oldValue, newValue proto.Message) bool {
	typedOldValue, err1 := castNSMEndpointValue(key, oldValue)
	typedNewValue, err2 := castNSMEndpointValue(key, newValue)
	if err1 != nil || err2 != nil {
		return false
	}
	return da.descriptor.ValueComparator(key, typedOldValue, typedNewValue)
}

func (da *NSMEndpointDescriptorAdapter) Validate(key string, value proto.Message) (err error) {
	typedValue, err := castNSMEndpointValue(key, value)
	if err != nil {
		return err
	}
	return da.descriptor.Validate(key, typedValue)
}

func (da *NSMEndpointDescriptorAdapter) Create(key string, value proto.Message) (metadata Metadata, err error) {
	typedValue, err := castNSMEndpointValue(key, value)
	if err != nil {
		return nil, err
	}
	return da.descriptor.Create(key, typedValue)
}

func (da *NSMEndpointDescriptorAdapter) Update(key string, oldValue, newValue proto.Message, oldMetadata Metadata) (newMetadata Metadata, err error) {
	oldTypedValue, err := castNSMEndpointValue(key, oldValue)
	if err != nil {
		return nil, err
	}
	newTypedValue, err := castNSMEndpointValue(key, newValue)
	if err != nil {
		return nil, err
	}
	typedOldMetadata, err := castNSMEndpointMetadata(key, oldMetadata)
	if err != nil {
		return nil, err
	}
	return da.descriptor.Update(key, oldTypedValue, newTypedValue, typedOldMetadata)
}

func (da *NSMEndpointDescriptorAdapter) Delete(key string, value proto.Message, metadata Metadata) error {
	typedValue, err := castNSMEndpointValue(key, value)
	if err != nil {
		return err
	}
	typedMetadata, err := castNSMEndpointMetadata(key, metadata)
	if err != nil {
		return err
	}
	return da.descriptor.Delete(key, typedValue, typedMetadata)
}

func (da *NSMEndpointDescriptorAdapter) UpdateWithRecreate(key string, oldValue, newValue proto.Message, metadata Metadata) bool {
	oldTypedValue, err := castNSMEndpointValue(key, oldValue)
	if err != nil {
		return true
	}
	newTypedValue, err := castNSMEndpointValue(key, newValue)
	if err != nil {
		return true
	}
	typedMetadata, err := castNSMEndpointMetadata(key, metadata)
	if err != nil {
		return true
	}
	return da.descriptor.UpdateWithRecreate(key, oldTypedValue, newTypedValue, typedMetadata)
}

func (da *NSMEndpointDescriptorAdapter) Retrieve(correlate []KVWithMetadata) ([]KVWithMetadata, error) {
	var correlateWithType []NSMEndpointKVWithMetadata
	for _, kvpair := range correlate {
		typedValue, err := castNSMEndpointValue(kvpair.Key, kvpair.Value)
		if err != nil {
			continue
		}
		typedMetadata, err := castNSMEndpointMetadata(kvpair.Key, kvpair.Metadata)
		if err != nil {
			continue
		}
		correlateWithType = append(correlateWithType,
			NSMEndpointKVWithMetadata{
				Key:      kvpair.Key,
				Value:    typedValue,
				Metadata: typedMetadata,
				Origin:   kvpair.Origin,
			})
	}

	typedValues, err := da.descriptor.Retrieve(correlateWithType)
	if err != nil {
		return nil, err
	}
	var values []KVWithMetadata
	for _, typedKVWithMetadata := range typedValues {
		kvWithMetadata := KVWithMetadata{
			Key:      typedKVWithMetadata.Key,
			Metadata: typedKVWithMetadata.Metadata,
			Origin:   typedKVWithMetadata.Origin,
		}
		kvWithMetadata.Value = typedKVWithMetadata.Value
		values = append(values, kvWithMetadata)
	}
	return values, err
}

func (da *NSMEndpointDescriptorAdapter) DerivedValues(key string, value proto.Message) []KeyValuePair {
	typedValue, err := castNSMEndpointValue(key, value)
	if err != nil {
		return nil
	}
	return da.descriptor.DerivedValues(key, typedValue)
}

func (da *NSMEndpointDescriptorAdapter) Dependencies(key string, value proto.Message) []Dependency {
	typedValue, err := castNSMEndpointValue(key, value)
	if err != nil {
		return nil
	}
	return da.descriptor.Dependencies(key, typedValue)
}

////////// Helper methods //////////

func castNSMEndpointValue(key string, value proto.Message) (*nsm.NetworkServiceEndpoint, error) {
	typedValue, ok := value.(*nsm.NetworkServiceEndpoint)
	if !ok {
		return nil, ErrInvalidValueType(key, value)
	}
	return typedValue, nil
}

func castNSMEndpointMetadata(key string, metadata Metadata) (*nsmetadata.NsmEndpointMetadata, error) {
	if metadata == nil {
		return nil, nil
	}
	typedMetadata, ok := metadata.(*nsmetadata.NsmEndpointMetadata)
	if !ok {
		return nil, ErrInvalidMetadataType(key)
	}
	return typedMetadata, nil
}
