/*
 * Copyright (c) 2019 PANTHEON.tech s.r.o. All rights reserved.
 *
 * CNF-NSM License. For licensing terms please contact sales@pantheon.tech.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "go.cdnf.io/cnf-nsm/plugins/crdplugin/pkg/apis/pantheontech/v1"
	"go.cdnf.io/cnf-nsm/plugins/crdplugin/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type PantheonV1Interface interface {
	RESTClient() rest.Interface
	CNFConfigurationsGetter
}

// PantheonV1Client is used to interact with features provided by the pantheon.tech group.
type PantheonV1Client struct {
	restClient rest.Interface
}

func (c *PantheonV1Client) CNFConfigurations(namespace string) CNFConfigurationInterface {
	return newCNFConfigurations(c, namespace)
}

// NewForConfig creates a new PantheonV1Client for the given config.
func NewForConfig(c *rest.Config) (*PantheonV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &PantheonV1Client{client}, nil
}

// NewForConfigOrDie creates a new PantheonV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *PantheonV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new PantheonV1Client for the given RESTClient.
func New(c rest.Interface) *PantheonV1Client {
	return &PantheonV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *PantheonV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
