/*
 * Copyright (c) 2019 PANTHEON.tech s.r.o. All rights reserved.
 *
 * CNF-NSM License. For licensing terms please contact sales@pantheon.tech.
 */

// Code generated by client-gen. DO NOT EDIT.

// Package fake has the automatically generated clients.
package fake
