/*
 * Copyright (c) 2019 PANTHEON.tech s.r.o. All rights reserved.
 *
 * CNF-NSM License. For licensing terms please contact sales@pantheon.tech.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "go.cdnf.io/cnf-nsm/plugins/crdplugin/pkg/client/clientset/versioned/typed/pantheontech/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePantheonV1 struct {
	*testing.Fake
}

func (c *FakePantheonV1) CNFConfigurations(namespace string) v1.CNFConfigurationInterface {
	return &FakeCNFConfigurations{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePantheonV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
